# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-06T12:56:15+00:00

from __future__ import annotations
from typing import Annotated, Any
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from enum import Enum, IntEnum
from uuid import UUID


class Error1(BaseModel):
    code: Annotated[str, Field(examples=["IMAGE_FORENSICS:FILE_TOO_LARGE"])]
    """
    Stable machine-readable error code.
    """
    message: str
    """
    Human-readable explanation, safe to log.
    """
    source_host: Annotated[str | None, Field(alias="sourceHost")] = None
    """
    For URL-based endpoints, the host that could not be resolved.
    """
    user_message: Annotated[str | None, Field(alias="userMessage")] = None
    """
    A display-friendly variant of the message (URL-based endpoints only).
    """


class Error(BaseModel):
    """
    Standard error envelope returned by every endpoint on failure.
    """

    error: Error1


class Verdict(Enum):
    """
    Overall classification of the media.
    - `real` — no manipulation detected
    - `ai_generated` — produced by a generative model
    - `ai_edited` — a real asset modified with AI tools
    - `digitally_edited` — conventional (non-AI) editing
    - `unknown` — the analysis was inconclusive

    """

    real = "real"
    ai_generated = "ai_generated"
    ai_edited = "ai_edited"
    digitally_edited = "digitally_edited"
    unknown = "unknown"


class JobStatus(Enum):
    """
    Lifecycle state of an asynchronous job.
    """

    queued = "Queued"
    processing = "Processing"
    completed = "Completed"
    failed = "Failed"
    cancelled = "Cancelled"


class Modality(Enum):
    """
    The kind of media being submitted.
    """

    image = "image"
    audio = "audio"
    video = "video"


class VoiceWorkflowType(IntEnum):
    """
    Which voice workflow to run:
    - `1` — Transcription only
    - `2` — Intelligence (text analysis) only
    - `3` — Combined transcription + intelligence
    - `4` — AI-voice detection only (default)

    """

    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4


class Generators(RootModel[dict[str, Any] | None]):
    root: dict[str, Any] | None
    """
    Generator attribution as a map of generator name → score (0–1), e.g.
    `{ "midjourney": 0.95 }`. Keys are returned dynamically by the detector.
    Null on basic plans.

    """


class Significance(Enum):
    """
    How strongly this finding should weigh in a manipulation assessment.
    """

    info = "info"
    notable = "notable"
    warning = "warning"


class MetadataFinding(BaseModel):
    """
    One user-facing metadata finding derived from the image's embedded metadata.
    """

    kind: str
    """
    Stable machine key for the finding. Current kinds: `editingSoftware`,
    `cameraInfo`, `createdDate`, `modifiedDate`, `gpsPresent` (presence only —
    coordinates are never returned), and `noMetadata` (the image carries no
    metadata, common for AI generated or re-saved images). New kinds may be
    added over time.

    """
    value: str | None = None
    """
    Optional display value, e.g. `Adobe Photoshop 24.0` or `Canon EOS R5`.
    """
    significance: Significance
    """
    How strongly this finding should weigh in a manipulation assessment.
    """


class ImageBatchStatus(Enum):
    """
    Batch-level state. `CompletedWithErrors` means the batch finished but at least one image failed — those images were refunded. The last four are terminal.
    """

    accepted = "Accepted"
    processing = "Processing"
    completed = "Completed"
    completed_with_errors = "CompletedWithErrors"
    cancelled = "Cancelled"
    failed = "Failed"


class ImageBatchItemStatus(Enum):
    """
    Per-image state within a batch.
    """

    queued = "Queued"
    processing = "Processing"
    completed = "Completed"
    failed = "Failed"
    cancelled = "Cancelled"


class ImageBatch(BaseModel):
    batch_id: Annotated[UUID | None, Field(alias="batchId")] = None
    status: ImageBatchStatus | None = None
    item_count: Annotated[int | None, Field(alias="itemCount")] = None
    completed_count: Annotated[int | None, Field(alias="completedCount")] = None
    failed_count: Annotated[int | None, Field(alias="failedCount")] = None
    cancelled_count: Annotated[int | None, Field(alias="cancelledCount")] = None
    queued_count: Annotated[int | None, Field(alias="queuedCount")] = None
    processing_count: Annotated[int | None, Field(alias="processingCount")] = None
    progress_percent: Annotated[int | None, Field(alias="progressPercent")] = None
    """
    0–100, derived from the per-image counts.
    """
    credits_charged: Annotated[int | None, Field(alias="creditsCharged")] = None
    credits_per_item: Annotated[int | None, Field(alias="creditsPerItem")] = None
    credits_refunded: Annotated[int | None, Field(alias="creditsRefunded")] = None
    """
    Credits returned for images that failed or were cancelled.
    """
    external_id: Annotated[str | None, Field(alias="externalId")] = None
    accepted_at: Annotated[AwareDatetime | None, Field(alias="acceptedAt")] = None
    started_at: Annotated[AwareDatetime | None, Field(alias="startedAt")] = None
    completed_at: Annotated[AwareDatetime | None, Field(alias="completedAt")] = None
    is_terminal: Annotated[bool | None, Field(alias="isTerminal")] = None
    """
    True once the batch will not change again. Stop polling.
    """


class ImageBatchPage(BaseModel):
    items: list[ImageBatch] | None = None
    skip: int | None = None
    take: int | None = None
    total_count: Annotated[int | None, Field(alias="totalCount")] = None


class ImageBatchCancelResult(BaseModel):
    cancelled_items: Annotated[int | None, Field(alias="cancelledItems")] = None
    """
    Images that were still waiting and have now been cancelled.
    """
    credits_refunded: Annotated[int | None, Field(alias="creditsRefunded")] = None
    """
    Credits returned for those images only.
    """


class ImageDeepAnalysis(BaseModel):
    """
    Detailed analysis narrative and findings. Null on basic plans and when the
    detection ran without deep analysis.

    """

    agreement: str | None = None
    """
    How strongly the detection signals agree with each other.
    """
    confidence: str | None = None
    """
    Narrative confidence statement for the deep analysis.
    """
    key_indicators: Annotated[list[str] | None, Field(alias="keyIndicators")] = None
    """
    The strongest signals behind the verdict.
    """
    detailed_reasoning: Annotated[str | None, Field(alias="detailedReasoning")] = None
    """
    Full analysis narrative.
    """
    visual_patterns: Annotated[list[str] | None, Field(alias="visualPatterns")] = None
    """
    Visual artifacts and patterns observed in the image.
    """
    recommendations: list[str] | None = None
    """
    Suggested next steps for verifying the image.
    """
    metadata_findings: Annotated[list[MetadataFinding] | None, Field(alias="metadataFindings")] = (
        None
    )
    """
    Curated findings from the image's embedded metadata.
    """


class Stage(Enum):
    """
    Which analysis stage decided the verdict.
    """

    full_image = "full_image"
    face_crop = "face_crop"
    full_image_no_face = "full_image_no_face"
    raw = "raw"


class ImageFace(BaseModel):
    """
    One detected face, located in original image pixels.
    """

    x: float
    """
    Left edge of the face rectangle, in pixels.
    """
    y: float
    """
    Top edge of the face rectangle, in pixels.
    """
    width: float
    height: float
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Confidence that this region is a face.
    """
    deepfake_score: Annotated[float, Field(alias="deepfakeScore", ge=0.0, le=1.0)]
    """
    Likelihood this face is synthetic, from 0 to 1.
    """


class VoiceDetectionChunk(BaseModel):
    """
    One analysis window of the audio timeline.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    index: int | None = None
    """
    Zero-based position in the timeline.
    """
    chunk: str | None = None
    """
    Human-readable time range label, e.g. `0-4s`.
    """
    result: str | None = None
    """
    Window label as decided by the detector (`real` or `fake`).
    """
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """
    Confidence in this window's own label, measured as distance past the decision boundary (same semantics as `detectionConfidence`).
    """
    score: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """
    This window's raw fakeness (`p_fake`), uncalibrated. Not a probability.
    """
    start_s: float | None = None
    """
    Window start in seconds.
    """
    end_s: float | None = None
    """
    Window end in seconds.
    """
    llr: float | None = None
    """
    Window log-likelihood ratio; positive leans genuine. Absent when the detector did not report one.
    """
    speech_ratio: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """
    Fraction of the window that contained speech.
    """
    quality_label: str | None = None
    """
    Detector's quality label for the window.
    """
    excluded: bool | None = None
    """
    True when this window was scored but left out of the file-level aggregate.
    """


class JobSubmitResponse(BaseModel):
    """
    Returned when an asynchronous fact-checking job is accepted.
    """

    job_id: Annotated[UUID, Field(alias="jobId")]
    """
    Identifier to poll for status and results.
    """
    status: JobStatus | None = None
    credits_reserved: Annotated[int, Field(alias="creditsReserved")]
    """
    Credits held pending completion; confirmed on success and refunded on failure/cancel.
    """


class VideoSubmitResponse(BaseModel):
    """
    Returned when a video job is accepted.
    """

    job_id: Annotated[UUID, Field(alias="jobId")]
    """
    Identifier to poll for status and results.
    """
    credits_reserved: Annotated[int, Field(alias="creditsReserved")]
    """
    Credits held pending completion; confirmed on success and refunded on failure/cancel.
    """


class VideoResult(BaseModel):
    """
    Populated on a video job once `status` is `Completed`.
    """

    verdict: Verdict
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    is_ai_generated: Annotated[bool, Field(alias="isAiGenerated")]
    frames_analyzed: Annotated[int, Field(alias="framesAnalyzed")]
    duration_seconds: Annotated[float | None, Field(alias="durationSeconds")] = None
    summary: str | None = None
    """
    Short human-readable summary of the finding.
    """
    has_detailed_report: Annotated[bool, Field(alias="hasDetailedReport")]
    """
    True when a detailed report is available. False on basic plans.
    """


class VideoJob(BaseModel):
    id: UUID
    file_name: Annotated[str, Field(alias="fileName")]
    file_size_bytes: Annotated[int | None, Field(alias="fileSizeBytes")] = None
    duration_seconds: Annotated[float | None, Field(alias="durationSeconds")] = None
    status: JobStatus
    progress: Annotated[int, Field(ge=0, le=100)]
    """
    Percent complete.
    """
    status_message: Annotated[str | None, Field(alias="statusMessage")] = None
    credits_reserved: Annotated[int, Field(alias="creditsReserved")]
    credits_used: Annotated[int, Field(alias="creditsUsed")]
    frames_analyzed: Annotated[int | None, Field(alias="framesAnalyzed")] = None
    processing_time_ms: Annotated[int, Field(alias="processingTimeMs")]
    error_message: Annotated[str | None, Field(alias="errorMessage")] = None
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    modified_at: Annotated[AwareDatetime | None, Field(alias="modifiedAt")] = None
    result: VideoResult | None = None
    """
    Null until the job completes.
    """


class ProvenanceUrl(BaseModel):
    url: str
    page_title: Annotated[str | None, Field(alias="pageTitle")] = None
    first_seen_at: Annotated[AwareDatetime | None, Field(alias="firstSeenAt")] = None
    match_type: Annotated[str | None, Field(alias="matchType")] = None
    """
    How the media matched this URL, e.g. `full`, `partial`, `page`, `entity`.
    """
    relevance: str | None = None
    """
    Assessed relevance — `high`, `medium`, or `low`.
    """


class ProvenanceItem(BaseModel):
    """
    A domain where the media (or closely matching media) was found.
    """

    domain: Annotated[str, Field(examples=["bbc.com"])]
    tier: str
    """
    Source tier — `authoritative`, `news`, `social`, or `unknown`.
    """
    urls: list[ProvenanceUrl]
    is_earliest_seen: Annotated[bool | None, Field(alias="isEarliestSeen")] = None
    """
    True for the earliest-known appearance across the result.
    """


class Claim(BaseModel):
    """
    A checkable claim extracted from audio/video. Null/absent for image jobs.
    """

    claim_text: Annotated[str, Field(alias="claimText")]
    verbatim_quote: Annotated[str | None, Field(alias="verbatimQuote")] = None
    verdict: str | None = None
    """
    Assessment — `supported`, `contradicted`, `mixed`, or `unverified`.
    """
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    speaker: str | None = None


class FactCheckResult(BaseModel):
    """
    Populated on a fact-checking job once `status` is `Completed`. Additional fields may be
    present for detailed reports — clients should ignore unknown fields (see Versioning).

    """

    modality: Modality
    has_detailed_report: Annotated[bool, Field(alias="hasDetailedReport")]
    summary: str
    """
    One-paragraph synthesis of the finding.
    """
    provenance: list[ProvenanceItem]
    """
    Domains where the media was found, grouped by source.
    """
    claims: list[Claim] | None = None
    """
    Extracted claims with verdicts (audio/video only).
    """
    transcript: str | None = None
    """
    Diarized transcript (audio/video only).
    """


class FactCheckJob(BaseModel):
    id: UUID
    modality: Modality
    file_name: Annotated[str, Field(alias="fileName")]
    file_size_bytes: Annotated[int | None, Field(alias="fileSizeBytes")] = None
    duration_seconds: Annotated[float | None, Field(alias="durationSeconds")] = None
    status: JobStatus
    progress: Annotated[int, Field(ge=0, le=100)]
    status_message: Annotated[str | None, Field(alias="statusMessage")] = None
    credits_reserved: Annotated[int, Field(alias="creditsReserved")]
    credits_used: Annotated[int, Field(alias="creditsUsed")]
    processing_time_ms: Annotated[int, Field(alias="processingTimeMs")]
    error_message: Annotated[str | None, Field(alias="errorMessage")] = None
    user_context: Annotated[str | None, Field(alias="userContext")] = None
    """
    The context you supplied at submit, echoed back.
    """
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    modified_at: Annotated[AwareDatetime | None, Field(alias="modifiedAt")] = None
    result: FactCheckResult | None = None
    """
    Null until the job completes.
    """


class ImageForensicsCreditInfo(BaseModel):
    """
    Credit balance and the live image-analysis limits for your account.
    """

    current_balance: Annotated[int, Field(alias="currentBalance")]
    """
    Credits available on the account.
    """
    credit_cost_per_image: Annotated[int, Field(alias="creditCostPerImage")]
    """
    Credits charged per image on the realtime tier.
    """
    can_use_feature: Annotated[bool, Field(alias="canUseFeature")]
    """
    True when image forensics is enabled for the account AND the balance covers one image.
    """
    max_file_size_mb: Annotated[int, Field(alias="maxFileSizeMB")]
    """
    Maximum size of a single image, in MB.
    """
    allowed_file_formats: Annotated[str, Field(alias="allowedFileFormats")]
    """
    Comma-separated list of accepted file extensions.
    """
    can_use_batch: Annotated[bool | None, Field(alias="canUseBatch")] = None
    """
    True when the batch tier is available. Independent of canUseFeature — realtime analysis can be enabled while batch is not.
    """
    batch_credit_cost_per_image: Annotated[int | None, Field(alias="batchCreditCostPerImage")] = (
        None
    )
    """
    Credits charged per image on the batch tier. Compare with creditCostPerImage to show the saving.
    """
    batch_max_size: Annotated[int | None, Field(alias="batchMaxSize")] = None
    """
    Maximum images accepted in one batch submission.
    """


class VoiceAnalysisCreditInfo(BaseModel):
    """
    Credit balance and the live audio limits for your account. Audio is priced per workflow, so each workflow carries its own cost and its own affordability flag.
    """

    tenant_credits: Annotated[int, Field(alias="tenantCredits")]
    """
    Credits available on the account.
    """
    transcription_cost_per_call: Annotated[int | None, Field(alias="transcriptionCostPerCall")] = (
        None
    )
    """
    Credits charged for the transcription-only workflow.
    """
    intelligence_cost_per_call: Annotated[int | None, Field(alias="intelligenceCostPerCall")] = None
    """
    Credits charged for the intelligence-only workflow.
    """
    combined_cost: Annotated[int | None, Field(alias="combinedCost")] = None
    """
    Credits charged for the combined transcription + intelligence workflow.
    """
    ai_detection_cost_per_call: Annotated[int | None, Field(alias="aiDetectionCostPerCall")] = None
    """
    Credits charged for the AI-voice detection workflow (the default).
    """
    can_use_transcription: Annotated[bool | None, Field(alias="canUseTranscription")] = None
    """
    True when that workflow is enabled AND the balance covers one call.
    """
    can_use_intelligence: Annotated[bool | None, Field(alias="canUseIntelligence")] = None
    can_use_combined: Annotated[bool | None, Field(alias="canUseCombined")] = None
    can_use_ai_detection: Annotated[bool | None, Field(alias="canUseAiDetection")] = None
    max_file_size_mb: Annotated[int, Field(alias="maxFileSizeMB")]
    """
    Maximum size of a single audio file, in MB.
    """
    allowed_file_formats: Annotated[str, Field(alias="allowedFileFormats")]
    """
    Comma-separated list of accepted file extensions.
    """
    can_use_batch_upload: Annotated[bool | None, Field(alias="canUseBatchUpload")] = None
    """
    True when more than one file may be submitted at a time.
    """
    max_batch_size: Annotated[int | None, Field(alias="maxBatchSize")] = None
    """
    Maximum files accepted in one submission.
    """


class VideoForensicsCreditInfo(BaseModel):
    """
    Credit balance and the live video limits for your account. Video is priced per analyzed frame, so cost depends on both duration and the sampling rate.
    """

    current_balance: Annotated[int, Field(alias="currentBalance")]
    """
    Credits available on the account.
    """
    credit_cost_per_frame: Annotated[int, Field(alias="creditCostPerFrame")]
    """
    Credits charged per analyzed frame.
    """
    max_video_length_seconds: Annotated[int | None, Field(alias="maxVideoLengthSeconds")] = None
    """
    Longest video the account may submit, in seconds.
    """
    max_credits_per_video_derived: Annotated[
        int | None, Field(alias="maxCreditsPerVideoDerived")
    ] = None
    """
    What maxVideoLengthSeconds currently costs at the live pricing (length x fps x cost per frame) — provided so a client does not have to repeat the multiplication.
    """
    frames_per_second_to_analyze: Annotated[int | None, Field(alias="framesPerSecondToAnalyze")] = (
        None
    )
    """
    Frames sampled per second of video. Drives both the credit estimate and the analysis itself.
    """
    max_file_size_mb: Annotated[int, Field(alias="maxFileSizeMB")]
    """
    Maximum size of a single video, in MB.
    """
    allowed_file_formats: Annotated[str, Field(alias="allowedFileFormats")]
    """
    Comma-separated list of accepted file extensions.
    """
    max_videos_per_day: Annotated[int | None, Field(alias="maxVideosPerDay")] = None
    """
    Daily submission cap for the account. Zero when no daily cap applies.
    """
    videos_used_today: Annotated[int | None, Field(alias="videosUsedToday")] = None
    """
    Videos submitted so far in the current UTC day, to pair with maxVideosPerDay.
    """
    can_use_feature: Annotated[bool, Field(alias="canUseFeature")]
    """
    True when video forensics is enabled for the account AND the balance covers a video.
    """


class FactCheckingCreditInfo(BaseModel):
    """
    Credit balance and the live fact-checking limits for your account. Cost depends on the modality, and on duration for audio and video.
    """

    current_balance: Annotated[int, Field(alias="currentBalance")]
    """
    Credits available on the account.
    """
    credit_cost_per_image: Annotated[int | None, Field(alias="creditCostPerImage")] = None
    """
    Credits charged to fact-check one image.
    """
    credit_cost_per_audio_minute: Annotated[int | None, Field(alias="creditCostPerAudioMinute")] = (
        None
    )
    """
    Credits charged per minute of audio.
    """
    credit_cost_per_video_minute: Annotated[int | None, Field(alias="creditCostPerVideoMinute")] = (
        None
    )
    """
    Credits charged per minute of video.
    """
    max_credits_per_job: Annotated[int | None, Field(alias="maxCreditsPerJob")] = None
    """
    Ceiling on what any single job may cost, however long the media is.
    """
    max_file_size_mb: Annotated[int, Field(alias="maxFileSizeMB")]
    """
    Maximum size of a single file, in MB.
    """
    allowed_file_formats: Annotated[str, Field(alias="allowedFileFormats")]
    """
    Comma-separated list of accepted file extensions.
    """
    can_use_feature: Annotated[bool, Field(alias="canUseFeature")]
    """
    True when fact-checking is enabled for the account AND the balance covers a job.
    """


class DocumentType(Enum):
    """
    Optional hint for the kind of document being submitted. When omitted — or when the value is
    not one of these — the pipeline classifies the document itself.
    - `bank_statement` — a bank account statement
    - `salary_cert` — a salary certificate
    - `invoice_po` — an invoice or purchase order
    - `kyc_id` — a KYC identity document
    - `financials` — company financial statements
    - `plane_ticket` — an airline ticket or itinerary

    """

    bank_statement = "bank_statement"
    salary_cert = "salary_cert"
    invoice_po = "invoice_po"
    kyc_id = "kyc_id"
    financials = "financials"
    plane_ticket = "plane_ticket"


class DocumentStatus(Enum):
    """
    Lifecycle status — of the analysis as a whole, and of each of its two branches.
    - `processing` — accepted and still running
    - `completed` — finished
    - `failed` — could not be completed

    """

    processing = "processing"
    completed = "completed"
    failed = "failed"


class DocumentMediaKind(Enum):
    """
    What the uploaded bytes actually are, derived server-side from the file's signature rather
    than its name or declared content type.
    - `pdf` — a PDF document
    - `image` — a single document-page image

    """

    pdf = "pdf"
    image = "image"


class DocumentFusedVerdict(Enum):
    """
    The headline decision for the whole document — the one field to branch on.
    - `accept` — no evidence of tampering or AI generation
    - `review` — signals worth a human look
    - `reject` — strong evidence the document is not genuine
    - `insufficient_quality` — the document could not be assessed

    """

    accept = "accept"
    review = "review"
    reject = "reject"
    insufficient_quality = "insufficient_quality"


class DocumentRefundReason(Enum):
    """
    Why the credit for this analysis was returned. Present only on a refunded analysis, where
    `creditsUsed` is `0`.
    - `no_usable_output` — neither branch produced a usable result
    - `stale_timeout` — the analysis stalled and was timed out
    - `submission_failed` — it never started

    """

    no_usable_output = "no_usable_output"
    stale_timeout = "stale_timeout"
    submission_failed = "submission_failed"


class DocumentPageVerdict(Enum):
    """
    A single page's headline. Deliberately a different vocabulary from the document-level
    `fusedVerdict` — this describes one page, not the decision about the document.
    - `authentic` — no localized edits and no sign of AI generation
    - `edited` — localized editing was found on the page
    - `ai_generated` — the page itself appears to be AI-generated

    """

    authentic = "authentic"
    edited = "edited"
    ai_generated = "ai_generated"


class DocumentPageAiStatus(Enum):
    """
    Outcome of the page's AI-generation check. It is additive — it never fails the page, so a
    non-`completed` status is normal and the page verdict still stands.
    - `not_run` — the check did not run
    - `skipped_edited` — skipped because the page was already found to be edited
    - `completed` — a verdict was produced (`aiVerdict`)
    - `failed` — the check could not complete; see `errorCode`

    """

    not_run = "not_run"
    skipped_edited = "skipped_edited"
    completed = "completed"
    failed = "failed"


class DocumentPageAiVerdict(Enum):
    """
    The AI-generation check's verdict for a page. Only `ai_generated` escalates a page's
    headline `verdict`.
    - `real` — no sign of AI generation
    - `ai_generated` — the page appears wholly AI-generated
    - `ai_edited` — AI-assisted editing
    - `digitally_edited` — conventional digital editing

    """

    real = "real"
    ai_generated = "ai_generated"
    ai_edited = "ai_edited"
    digitally_edited = "digitally_edited"


class DocumentFinding(BaseModel):
    """
    A single detector signal within a feature lane.
    """

    type: str
    """
    The kind of signal, e.g. `iban_invalid_checksum`, `arithmetic_mismatch`, `xray_scanned_redaction`.
    """
    expected: str | None = None
    """
    The expected value, when the finding is a mismatch.
    """
    got: str | None = None
    """
    The observed value, when the finding is a mismatch.
    """
    bbox: list[float] | None = None
    """
    NORMALIZED page box `[x0, y0, x1, y1]`, each value 0–1. A different coordinate space from `DocumentAnalysisPage.editedRegions`, which is in original-image pixels — divide those by the page dimensions to draw both on one overlay.
    """
    page: int | None = None
    """
    1-based page number the finding is on.
    """
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    note: str | None = None
    """
    Free-text note; may carry recovered hidden content as `hidden:'…'`.
    """


class DocumentFeatureScore(BaseModel):
    """
    One feature lane of the forensics verdict (tampering / consistency / anomaly).
    """

    score: float
    """
    Raw lane score (0–1).
    """
    calibrated_probability: Annotated[float, Field(alias="calibratedProbability", ge=0.0, le=1.0)]
    """
    Calibrated probability for this lane (0–1).
    """
    reliability: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    How reliable this lane's signal is for this document (0–1). Below ~0.7, treat it as low-confidence.
    """
    soft_score_calibrated: Annotated[bool | None, Field(alias="softScoreCalibrated")] = None
    """
    Whether the lane's score is calibrated.
    """
    findings: list[DocumentFinding]
    """
    The individual detector signals behind the lane score.
    """
    evidence_uris: Annotated[list[str], Field(alias="evidenceUris")]
    """
    Storage URIs of this lane's evidence rasters. Not publicly fetchable — read a crop through `GET /api/app/document-analysis/{id}/evidence` instead.
    """


class DocumentVerdict(BaseModel):
    """
    The document-level forensics verdict — three feature lanes plus their own fused conclusion.
    """

    doc_id: Annotated[str, Field(alias="docId")]
    doc_type: Annotated[str | None, Field(alias="docType")] = None
    doc_type_confidence: Annotated[
        float | None, Field(alias="docTypeConfidence", ge=0.0, le=1.0)
    ] = None
    tampering: DocumentFeatureScore | None = None
    """
    Tampering lane — overlays, painted-over regions, bad redactions, font substitution.
    """
    consistency: DocumentFeatureScore | None = None
    """
    Consistency lane — arithmetic, IBAN checksums, dates, cross-field agreement.
    """
    anomaly: DocumentFeatureScore | None = None
    """
    Anomaly lane — how far the document sits from others of its type.
    """
    fused_verdict: Annotated[DocumentFusedVerdict, Field(alias="fusedVerdict")]
    fused_probability: Annotated[float, Field(alias="fusedProbability", ge=0.0, le=1.0)]
    fusion_rationale: Annotated[str | None, Field(alias="fusionRationale")] = None
    """
    Explanation of this branch's verdict; may name the rule types that fired.
    """
    pipeline_versions: Annotated[dict[str, str] | None, Field(alias="pipelineVersions")] = None
    """
    Map of pipeline component → version, for reproducibility.
    """
    processed_at: Annotated[AwareDatetime | None, Field(alias="processedAt")] = None
    latency_ms: Annotated[int | None, Field(alias="latencyMs")] = None
    """
    This branch's latency in milliseconds.
    """


class DocumentAnalysisRegion(BaseModel):
    """
    One localized edited region on a page, in ORIGINAL-IMAGE PIXELS with a top-left origin, against the page's `pageWidth` / `pageHeight` — safe to draw directly on the raster served by `GET /api/app/document-analysis/{id}/pages/{pageNumber}/image`. Note this is NOT the normalized 0–1 space that `DocumentFinding.bbox` uses.
    """

    x: float
    """
    Left edge, in original-image pixels.
    """
    y: float
    """
    Top edge, in original-image pixels.
    """
    width: float
    height: float
    score: float
    """
    Max anomaly probability inside the region (0–1) — the number to badge the box with.
    """
    mean_score: Annotated[float, Field(alias="meanScore")]
    """
    Mean anomaly probability inside the region (0–1).
    """
    area_fraction: Annotated[float, Field(alias="areaFraction")]
    """
    Region area ÷ image area.
    """


class DocumentAnalysisPage(BaseModel):
    """
    One page's two legs — localized editing detection, then (on a clean page) the AI-generation check. Pages appear as they finish, so this list grows while the analysis runs.
    """

    page_number: Annotated[int, Field(alias="pageNumber")]
    """
    1-based page number.
    """
    verdict: DocumentPageVerdict | None = None
    """
    The page's headline. **Render this, not `localizedEditing`** — a wholly AI-generated page carries `localizedEditing: false`, because no region of it was edited. Null when the page has no localization result at all.
    """
    localized_editing: Annotated[bool | None, Field(alias="localizedEditing")] = None
    """
    The localization check's editing call — whether its whole-page score crossed `threshold`. Null when that leg failed.
    """
    editing_score: Annotated[float | None, Field(alias="editingScore", ge=0.0, le=1.0)] = None
    """
    Whole-page editing score (0–1); higher = more likely edited.
    """
    ai_status: Annotated[DocumentPageAiStatus, Field(alias="aiStatus")]
    ai_verdict: Annotated[DocumentPageAiVerdict | None, Field(alias="aiVerdict")] = None
    """
    Present only when `aiStatus` is `completed`.
    """
    ai_confidence: Annotated[float | None, Field(alias="aiConfidence", ge=0.0, le=1.0)] = None
    """
    Confidence in `aiVerdict` — **not** a probability that the page is AI-generated. Only meaningful read together with the verdict it belongs to.
    """
    error_code: Annotated[str | None, Field(alias="errorCode")] = None
    """
    Stable error code when one of the page's legs failed. Null otherwise.
    """
    completed_at: Annotated[AwareDatetime, Field(alias="completedAt")]
    edited_regions: Annotated[list[DocumentAnalysisRegion], Field(alias="editedRegions")]
    """
    Localized edited regions, strongest first (max 10). Empty when the page is clean or the localization leg failed.
    """
    page_width: Annotated[int | None, Field(alias="pageWidth")] = None
    """
    Pixel width of the raster the regions are expressed against — and of the exact raster the page-image endpoint serves, so boxes cannot drift from the image they are drawn on.
    """
    page_height: Annotated[int | None, Field(alias="pageHeight")] = None
    """
    Pixel height counterpart of `pageWidth`.
    """
    mean_confidence: Annotated[float | None, Field(alias="meanConfidence", ge=0.0, le=1.0)] = None
    """
    The localization check's self-estimated reliability of its map (0–1). Below ~0.7, present the regions as approximate.
    """
    threshold: float | None = None
    """
    Decision threshold the localization check ran with — context for `editingScore`.
    """
    has_image: Annotated[bool, Field(alias="hasImage")]
    """
    True when a stored page raster exists and `GET /api/app/document-analysis/{id}/pages/{pageNumber}/image` will serve it.
    """


class DocumentAnalysis(BaseModel):
    """
    One unified document analysis — the same shape whether the job is still running (`202`) or
    terminal (`200`), so a client renders partial and final results with one code path.

    Two verdicts, two vocabularies: the document-level `fusedVerdict`
    (`accept`/`review`/`reject`/`insufficient_quality`) is the overall decision, while a page's
    `verdict` (`authentic`/`edited`/`ai_generated`) describes that one page.

    """

    id: UUID
    """
    Analysis id — use it for `GET {id}` and the page-image / evidence endpoints.
    """
    doc_id: Annotated[str, Field(alias="docId")]
    """
    Pipeline document identifier (tenant-encoded).
    """
    file_name: Annotated[str | None, Field(alias="fileName")] = None
    """
    Original uploaded file name.
    """
    media_kind: Annotated[DocumentMediaKind, Field(alias="mediaKind")]
    doc_type: Annotated[str, Field(alias="docType")]
    """
    The classified (or supplied) document type — see `DocumentType` for the common values. Empty until classified, and empty when it could not be determined.
    """
    status: DocumentStatus
    forensics_status: Annotated[DocumentStatus, Field(alias="forensicsStatus")]
    pages_status: Annotated[DocumentStatus, Field(alias="pagesStatus")]
    fused_verdict: Annotated[str, Field(alias="fusedVerdict")]
    """
    The headline verdict once complete — see `DocumentFusedVerdict` for the values. Empty while processing.
    """
    fused_probability: Annotated[float, Field(alias="fusedProbability", ge=0.0, le=1.0)]
    """
    Risk score (0–1) behind `fusedVerdict`. It is the strongest signal that fired, never a blend of the branches.
    """
    fusion_rationale: Annotated[str, Field(alias="fusionRationale")]
    """
    Plain-language explanation of the verdict. Empty while processing.
    """
    stage_errors_json: Annotated[str | None, Field(alias="stageErrorsJson")] = None
    """
    Stage failures as a JSON-array-encoded **string**, e.g. `"[\\"forensics_timeout\\"]"` — parse it as JSON, and treat an unparseable value as a single unstructured error. Null when nothing failed.
    """
    pages_total: Annotated[int, Field(alias="pagesTotal")]
    """
    Total pages in the document.
    """
    pages_completed: Annotated[int, Field(alias="pagesCompleted")]
    """
    Pages finished so far.
    """
    pages_failed: Annotated[int, Field(alias="pagesFailed")]
    """
    Pages that errored.
    """
    credits_used: Annotated[int, Field(alias="creditsUsed")]
    """
    Credits charged for this analysis; `0` when the credit was refunded.
    """
    refund_reason: Annotated[DocumentRefundReason | None, Field(alias="refundReason")] = None
    """
    Present when the credit was returned.
    """
    completed_at: Annotated[AwareDatetime | None, Field(alias="completedAt")] = None
    """
    When the analysis became terminal. Null while processing.
    """
    doc_type_confidence: Annotated[
        float | None, Field(alias="docTypeConfidence", ge=0.0, le=1.0)
    ] = None
    """
    Confidence in `docType` (0–1); `0` when unknown.
    """
    processing_time_ms: Annotated[int | None, Field(alias="processingTimeMs")] = None
    """
    Forensics-branch wall-clock in milliseconds; `0` when unknown.
    """
    processed_at: Annotated[AwareDatetime | None, Field(alias="processedAt")] = None
    """
    When the forensics branch produced its verdict. Null when unknown.
    """
    has_original: Annotated[bool | None, Field(alias="hasOriginal")] = None
    """
    True while a retained copy of the uploaded document exists for this analysis.
    """
    verdict: DocumentVerdict | None = None
    """
    The full forensics verdict — feature lanes and findings. Null while that branch is still running, or if it never reported.
    """
    pages: list[DocumentAnalysisPage]
    """
    Per-page results; grows while the analysis runs.
    """


class DocumentAnalysisCreditInfo(BaseModel):
    """
    Credit balance and the live upload constraints for document analysis.
    """

    current_balance: Annotated[int, Field(alias="currentBalance")]
    """
    Credits available on the account.
    """
    credit_cost_per_document: Annotated[int, Field(alias="creditCostPerDocument")]
    """
    Credits charged per analysis.
    """
    max_batch_files: Annotated[int, Field(alias="maxBatchFiles")]
    """
    Maximum documents to submit in one batch (default 5).
    """
    analyze_concurrency: Annotated[int, Field(alias="analyzeConcurrency")]
    """
    Recommended number of concurrent `analyze` requests when working through a batch (default 3).
    """
    max_file_size_mb: Annotated[int, Field(alias="maxFileSizeMB")]
    """
    Maximum PDF size in MB (default 25).
    """
    max_image_size_mb: Annotated[int, Field(alias="maxImageSizeMB")]
    """
    Maximum image size in MB (default 10).
    """
    user_headroom_remaining: Annotated[int | None, Field(alias="userHeadroomRemaining")] = None
    """
    Credits left under the calling user's own cap. Null for a principal without one — an API token has no per-user cap, so it is always null for token callers.
    """
    can_use_feature: Annotated[bool, Field(alias="canUseFeature")]
    """
    True when document analysis is enabled for the account AND the balance covers one document.
    """


class DocumentError(BaseModel):
    """
    The error shape the document-analysis endpoints return for a rejected upload — a single human-readable message, without the `{ code, message }` envelope the other modalities use.
    """

    error: str
    """
    What went wrong, in plain language.
    """


class PaywallError(BaseModel):
    """
    Returned when a per-user credit cap has been reached.
    """

    code: str
    """
    `USER_CREDIT_LIMIT_REACHED`
    """
    feature: str
    """
    The feature the cap applies to, e.g. `document-analysis`.
    """
    redirect_url: Annotated[str | None, Field(alias="redirectUrl")] = None
    message: str


class ImageBatchSubmitResponse(BaseModel):
    """
    Acknowledgement that images were queued. Contains no verdicts.
    """

    batch_id: Annotated[UUID | None, Field(alias="batchId")] = None
    """
    Use this to poll status and fetch results.
    """
    status: ImageBatchStatus | None = None
    item_count: Annotated[int | None, Field(alias="itemCount")] = None
    """
    Number of images queued.
    """
    credits_charged: Annotated[int | None, Field(alias="creditsCharged")] = None
    """
    Total deducted now. Batch charges on acceptance, not on completion.
    """
    credits_per_item: Annotated[int | None, Field(alias="creditsPerItem")] = None
    """
    Rate applied to this batch, after any plan-specific pricing.
    """
    realtime_credits_per_item: Annotated[int | None, Field(alias="realtimeCreditsPerItem")] = None
    """
    The realtime rate, for comparison.
    """
    estimated_processing_window: Annotated[str | None, Field(alias="estimatedProcessingWindow")] = (
        None
    )
    """
    Human-readable hint about when the batch will be processed.
    """
    status_url: Annotated[str | None, Field(alias="statusUrl")] = None
    """
    Relative path to poll for status.
    """
    external_id: Annotated[str | None, Field(alias="externalId")] = None


class ImageFaceAnalysis(BaseModel):
    """
    How the verdict was reached at face level. When `stage` is `face_crop`, every
    detected face was scored individually and `faces` lists them (largest first) with
    `decidingFace` pointing at the face that determined the verdict. When the verdict
    was decided on the whole image (`full_image`, or `full_image_no_face` when no face
    was detected), `decidingFace` and `faces` are null by design.

    """

    stage: Stage
    """
    Which analysis stage decided the verdict.
    """
    full_image_score: Annotated[float | None, Field(alias="fullImageScore", ge=0.0, le=1.0)] = None
    """
    Whole image synthetic score from the first analysis stage.
    """
    deciding_face: Annotated[ImageFace | None, Field(alias="decidingFace")] = None
    """
    The face that determined the verdict; null when the whole image decided.
    """
    faces: list[ImageFace] | None = None
    """
    Every detected face, largest first; null when the whole image decided.
    """


class VoiceDetectionDetails(BaseModel):
    """
    Detection detail for the AI-voice workflow, keyed exactly as the detector reports it (snake_case). Every field is optional: which ones appear depends on the detector the platform runs for your account, and the set can grow without notice. Unknown keys are preserved. Other workflows (transcription, intelligence) carry their own keys here instead.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    provider: str | None = None
    """
    Identifier of the detector that produced this verdict, e.g. `raid_1b`. The platform selects the detector per account; this is an open set — do not hard-code it. Absent on the legacy detector.
    """
    detection_method: str | None = None
    """
    How the file verdict was aggregated from per-window scores (detector-specific label).
    """
    model_version: str | None = None
    """
    Detector checkpoint identifier, for reproducibility.
    """
    calibration_version: str | None = None
    """
    Identifier of the calibration the thresholds came from.
    """
    threshold_name: str | None = None
    """
    Name of the operating point the verdict was decided against.
    """
    response_type: str | None = None
    """
    Which wire contract the detector response was parsed as.
    """
    score: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """
    Percentile of this clip against the detector's own reference of genuine speech, with `score_basis` saying how it was derived. 0 = indistinguishable from genuine audio, 1 = more suspicious than all of it. This is the figure to show users and to threshold on: it carries no assumption about how common fakes are, and it means the same thing across detectors. Absent means unknown, never 0.
    """
    score_basis: str | None = None
    """
    How `score` was derived, e.g. `percentile_vs_genuine`. Only read `score` as a percentile when this says so.
    """
    p_fake: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """
    The detector's raw fakeness output. While `probability_calibrated` is false this is a monotone ranking, not a probability: a genuine clip can report 0.0009 here and still be near the decision boundary, because the boundary is not at 0.5. Do not display it as a percentage likelihood.
    """
    probability_calibrated: bool | None = None
    """
    True only when `p_fake` is a calibrated posterior probability. False on current detectors.
    """
    threshold_calibrated: bool | None = None
    """
    True when the decision threshold was fitted on a reference set rather than left at a default.
    """
    threshold_global_tau: float | None = None
    """
    The log-likelihood-ratio cut the file-level decision was made against.
    """
    global_llr_mean: float | None = None
    """
    Mean log-likelihood ratio over the scored windows; positive leans genuine. `global_llr_mean - threshold_global_tau` is the decision margin.
    """
    threshold_partial_tau: float | None = None
    """
    Cut for the partial (worst-windows) rule, when the detector evaluates one.
    """
    partial_llr_k_lowest_mean: float | None = None
    """
    Mean LLR of the `partial_k` most fake-leaning windows, measured against `threshold_partial_tau`.
    """
    partial_k: int | None = None
    """
    How many windows the partial statistic was drawn over.
    """
    threshold_fired_global: bool | None = None
    """
    Whether the global rule tripped. Absent means that rule was not evaluated, not that it passed.
    """
    threshold_fired_partial: bool | None = None
    """
    Whether the partial rule tripped. The verdict is fake if either rule fires. Absent means not evaluated.
    """
    overall_result: str | None = None
    """
    File-level label as the detector stated it (`real` or `fake`).
    """
    total_chunks: int | None = None
    """
    Windows the audio was split into.
    """
    real_chunks: int | None = None
    """
    Scored windows labelled genuine. Window tallies do not decide the file verdict; the aggregate LLR does.
    """
    fake_chunks: int | None = None
    """
    Scored windows labelled fake.
    """
    n_chunks_scored: int | None = None
    """
    Windows that contributed to the aggregate.
    """
    n_chunks_excluded: int | None = None
    """
    Windows scored but excluded from the aggregate (non-speech).
    """
    chunks_omitted: bool | None = None
    """
    True when the per-window timeline was suppressed for this account, so an empty `chunks` is not "nothing analysed".
    """
    chunks: list[VoiceDetectionChunk] | None = None
    """
    Per-window timeline, in order. May be empty or absent.
    """
    average_confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """
    Legacy field. Mean window fakeness, kept for compatibility; prefer `score`.
    """
    max_confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """
    Highest per-window confidence in that window's own verdict.
    """
    min_confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """
    Lowest per-window confidence in that window's own verdict.
    """
    low_confidence: bool | None = None
    """
    The clip was too short for the verdict to rest on much audio (it was tiled to fill one window). Surface this next to the verdict.
    """
    truncated: bool | None = None
    """
    The file exceeded the analysis ceiling and its tail was never scored; the verdict describes the analysed part only.
    """
    truncated_s: float | None = None
    """
    Seconds that were not analysed because of truncation. Present only when something was cut.
    """
    repeat_tiled: bool | None = None
    """
    True when the audio was repeated to fill the analysis window.
    """
    variable_length: bool | None = None
    """
    True when the detector scored the clip in a single variable-length pass instead of fixed windows.
    """
    audio_total_s: float | None = None
    """
    Duration of the submitted audio, in seconds.
    """
    audio_analyzed_s: float | None = None
    """
    Seconds of audio the detector analysed.
    """
    total_s: float | None = None
    """
    Duration of the source file in seconds (companion to `coverage_pct`).
    """
    analyzed_s: float | None = None
    """
    Seconds actually analysed (companion to `coverage_pct`).
    """
    coverage_s: float | None = None
    """
    Seconds of audio that fell inside some scored window.
    """
    coverage_pct: float | None = None
    """
    Share of the whole file that was covered by scored windows, as a percentage.
    """
    coverage_of_analyzed_pct: float | None = None
    """
    Share of the analysed span that was covered by scored windows, as a percentage.
    """
    window_s: float | None = None
    """
    Window length in seconds.
    """
    hop_s: float | None = None
    """
    Hop between consecutive windows in seconds.
    """
    mode: str | None = None
    """
    Sampling mode the detector ran (e.g. `sliding`, `random_k`, `full`).
    """
    inference_s: float | None = None
    """
    Model inference time in seconds.
    """
    timestamp_offset_s: float | None = None
    """
    Present when leading silence was trimmed; add it to window timestamps to map them back onto the original file.
    """
    warnings: list[str] | None = None
    """
    Run-specific caveats the detector raised. Absent when there are none.
    """
    mode_notes: list[str] | None = None
    """
    Human-readable notes about how this run was sampled.
    """
    file_name: str | None = None
    """
    The file name as received.
    """
    error_code: str | None = None
    """
    Machine-readable reason when `isSuccessful` is false (e.g. no clear speech). Open set.
    """


class ImageResult(BaseModel):
    id: UUID | None = None
    """
    Stable record ID for this image (null if the image failed to process).
    """
    file_name: Annotated[str, Field(alias="fileName")]
    """
    Original file name (or a derived name for URL inputs).
    """
    verdict: Verdict
    confidence: Annotated[float, Field(examples=[0.972], ge=0.0, le=1.0)]
    """
    Confidence in the verdict, from 0 to 1.
    """
    is_manipulated: Annotated[bool, Field(alias="isManipulated")]
    """
    Convenience flag — true when `verdict` is anything other than `real`.
    """
    credits_used: Annotated[int, Field(alias="creditsUsed")]
    """
    Credits charged for this image.
    """
    processing_time_ms: Annotated[int, Field(alias="processingTimeMs")]
    """
    Server-side processing time in milliseconds.
    """
    error_message: Annotated[str | None, Field(alias="errorMessage")] = None
    """
    Failure reason when this image could not be analyzed; otherwise null.
    """
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    deepfake_score: Annotated[float | None, Field(alias="deepfakeScore")] = None
    """
    Likelihood the image is a deepfake (0–1). Null on basic plans.
    """
    generators: Generators | None = None
    deep_analysis: Annotated[ImageDeepAnalysis | None, Field(alias="deepAnalysis")] = None
    face_analysis: Annotated[ImageFaceAnalysis | None, Field(alias="faceAnalysis")] = None
    """
    Face level analysis of the detection. Present only when face details are enabled
    on your account — contact us to enable it. Null otherwise, and null on images
    where the analysis did not run face by face.

    """


class ImageForensicsResponse(BaseModel):
    images: list[ImageResult]
    total_credits_used: Annotated[int, Field(alias="totalCreditsUsed")]
    total_processing_time_ms: Annotated[int, Field(alias="totalProcessingTimeMs")]
    is_successful: Annotated[bool, Field(alias="isSuccessful")]
    """
    True when at least one image was analyzed successfully.
    """
    error_message: Annotated[str | None, Field(alias="errorMessage")] = None
    has_detailed_report: Annotated[bool, Field(alias="hasDetailedReport")]
    """
    True when the response includes detailed fields (`generators`, `deepfakeScore`,
    `deepAnalysis`). False on basic plans, where those fields are null.

    """


class VoiceAnalysisResponse(BaseModel):
    is_successful: Annotated[bool, Field(alias="isSuccessful")]
    error_message: Annotated[str | None, Field(alias="errorMessage")] = None
    workflow_type: Annotated[str, Field(alias="workflowType")]
    """
    Name of the workflow that ran: `TranscriptionOnly`, `IntelligenceOnly`, `Combined` or `AiDetectionOnly`. Requests select the workflow with the numeric `VoiceWorkflowType`; the response echoes its name.
    """
    transcript: str | None = None
    """
    Transcribed text. Populated for Transcription and Combined workflows.
    """
    analysis: str | None = None
    """
    Intelligence analysis text. Populated for Intelligence and Combined workflows.
    """
    context_used: Annotated[str | None, Field(alias="contextUsed")] = None
    """
    The context hints that were applied, if any.
    """
    is_ai_detected: Annotated[bool | None, Field(alias="isAiDetected")] = None
    """
    Whether the voice is AI-generated. Populated for the AI-detection workflow.
    """
    detection_confidence: Annotated[
        float | None, Field(alias="detectionConfidence", ge=0.0, le=1.0)
    ] = None
    """
    How confident the detector is in the verdict it reported in `detectionClassification`, from 0 to 1. It measures how far past the decision boundary the audio landed — **not** the probability that the audio is AI-generated. Read `0.5` as "landed on the boundary, maximally uncertain", not as "50% likely fake", and never derive the opposite verdict's confidence as `1 - detectionConfidence`: both verdicts are reported at high confidence when they are far from the boundary. Use it to rank and to shade results; it is not a calibrated probability, so don't present it to end users as a percentage likelihood.
    """
    detection_classification: Annotated[str | None, Field(alias="detectionClassification")] = None
    """
    Classification label for detection, e.g. `real`, `suspicious`, or `fake`.
    """
    processing_time_ms: Annotated[int, Field(alias="processingTimeMs")]
    credits_used: Annotated[int, Field(alias="creditsUsed")]
    metadata: VoiceDetectionDetails | None = None
    """
    Workflow metadata. For the AI-detection workflow this is the detector's own detail, typed as `VoiceDetectionDetails`; other workflows carry their own keys here.
    """


class ImageBatchResult(BaseModel):
    item_id: Annotated[UUID | None, Field(alias="itemId")] = None
    ordinal: int | None = None
    """
    Position in the original submission, so results can be matched to inputs.
    """
    file_name: Annotated[str | None, Field(alias="fileName")] = None
    status: ImageBatchItemStatus | None = None
    error_code: Annotated[str | None, Field(alias="errorCode")] = None
    """
    Set when the image could not be analyzed. Its credits were refunded.
    """
    result: ImageResult | None = None
    """
    The verdict, once analyzed. Deep analysis, generator attribution and heatmap are always null on this path — those are realtime-only.
    """


class ImageBatchResultPage(BaseModel):
    items: list[ImageBatchResult] | None = None
    skip: int | None = None
    take: int | None = None
    total_count: Annotated[int | None, Field(alias="totalCount")] = None
